src/java/org/httpkit/server/WSDecoder.java
Frames with a payload length of 127 would cause WSDecoder to throw an
exception after going from PAYLOAD to FRAME_START as the opcode would
not match the conditions in FRAME_START. The fix was to set the variable 
"opcode" to -1 before returning to state FRAME_START. Another exception 
would be thrown on reading the final frame due to the first frame's 
opcode not being preserved. The fix was to add the variable 
"fragmentedOpCode" that would preserve the first frame's opcode. The 
changes should be in accordance with Section 5.4 of RFC 6455.
The ProtocolException in READ_8_LENGTH had a misleading statement. For
example, the max payload length can be greater than 4M. It now provides
a more informative message.
=> Fixing fragmented WebSocket messages

src/org/httpkit/client.clj
so that this succinct line works:
@(client/get url :status)
instead of awkwardly wrapping to #(:status %)
=> enable the use of keywords as callback funcs in requests,

src/org/httpkit/server.clj
The returned server thread could be used.
=> Changed run-server function to return server thread in meta

src/java/org/httpkit/server/RingHandler.java
Sending lots of small messages at a high rate to an http-kit websocket will sometimes create a chain of LinkedRunnable's long enough to cause a stack overflow on this line:
https://github.com/http-kit/http-kit/blob/73f82165c73d2a0599e610db8cb7a50de48d31cd/src/java/org/httpkit/server/RingHandler.java#L122
This pull request implements a loop to follow the chain in a single stack frame, avoiding the stack overflow.
=> LinkedRunnable.run: don't consume stack unnecessarily

src/org/httpkit/client.clj
Currently, if a multipart request has both form params and files, the former are lost when coercing the request. This PR fixes the issue.
=> HTTP client: keep form params in multipart requests

src/org/httpkit/client.clj, test/org/httpkit/client_test.clj
The `deliver-resp` helper function in `org.httpkit.client/request` catches Exception, but not Throwable. Any code in the callback that throws Throwable rather than Exception prevents the client thread from ever returning (so far as I can tell). That is unfortunate, because Clojure's `assert`, and `:pre` and `:post` conditions all throw Throwable rather than Exception, leading to some very hard to troubleshoot failures.
I believe this might be the problem behind these issues:
* https://github.com/http-kit/http-kit/issues/73
* https://github.com/http-kit/http-kit/issues/118
* https://github.com/http-kit/http-kit/issues/194
If not, they at least appear to describe behavior in http-kit similar to what made me look into this.
=> Catch Throwable when delivering response

src/java/org/httpkit/client/HttpClient.java
Prevent exception from being thrown calling setUseClientMode on a user-supplied client mode SSLEngine.
=> Do not set client mode on SSLEngine if already set.

src/java/org/httpkit/HttpUtils.java, src/java/org/httpkit/server/HttpDecoder.java, src/java/org/httpkit/server/HttpServer.java
Whenever cURL sends a POST request (on Mac and Linux), it sends the expect header, and then waits 1 second before sending the actual body. This fix allows the server to respond with the correct temporary status code (100) and accelerate the transfer of the body.
> POST / HTTP/1.1
> User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8y zlib/1.2.5
> Host: localhost:8080
> Accept: */*
> Content-Length: 4778
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< Content-Length: 0
< Server: http-kit
< Date: Fri, 07 Mar 2014 20:06:53 GMT
} [data not shown]
< HTTP/1.1 202 Accepted
< Content-Type: text/plain
< Content-Length: 4778
< Server: http-kit
< Date: Fri, 07 Mar 2014 20:06:53 GMT
=> Server can now respond to HTTP_1.1/Expect : 100-continue header 

src/org/httpkit/client.clj, test/org/httpkit/client_test.clj
Currently the client changes the request method to GET when following a
301, 302, or 303 redirect. This adds an :allow-unsafe-redirect-methods
request option that can be used to override this behaviour.
=> client: option to keep "unsafe" method on redirect

src/java/org/httpkit/client/HttpClient.java, src/java/org/httpkit/client/Request.java
With the current implementation, the actual connect timeout can be up to 2 seconds greater than the passed-in connection timeout; the patch tries to address this by using the time remaining for the the first queued request to expire as the actual timeout.
=> More accurate timeout handling

src/java/org/httpkit/server/HttpServer.java
when iterating the set,it’s not necessary to produce a array and then
iterate.
=> Remove unnecessary operation.

src/java/org/httpkit/server/HttpAtta.java, src/java/org/httpkit/server/HttpDecoder.java, src/java/org/httpkit/server/HttpServer.java, src/java/org/httpkit/server/ProxyProtocolOption.java, src/org/httpkit/server.clj, test/java/org/httpkit/server/MultiThreadHttpServerTest.java, test/java/org/httpkit/server/SingleThreadHttpServerTest.java
Add proxy protocol support. 
Some background about Proxy Protocol:
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt
Since AWS ELB does not support WebSocket using HTTP protocol. The work around is to use TCP with PROXY Protocol. 
This patch will add PROXY Protocol support.
=> Add Proxy Protocol support

history.md
This PR updates the release notes (`history.md`) for version 2.1.19, which is the latest stable version on Clojars as of today.
=> update release notes for version 2.1.19

src/java/org/httpkit/server/HttpServer.java
This commit adds `selector.wakeup()` calls after adding new PendingKeys to the
ConcurrentLinkedList; if we don't do this the main thread blocks on the
`selector.select` call and eventually times out.
This commit also cleans up the polling logic to read a little cleaner, I think.
Resolves #148 
cc @ptaoussanis
=> Remind the selector to wake up.

src/java/org/httpkit/server/WSDecoder.java
When sending frames of different types (opcodes) over websockets to the httpkit server, the type of frames is incorrectly set after fragmentation occurs. This is because `fragmentedOpCode` is never reset in `WSDecoder.java`. This pull request fixes the bug.
To reproduce the problem:
* Send a text frame to the server
* Send a fragmented binary frame to the server
* Send a text frame to the server
Notice that the final text frame is delivered as a binary frame. This obviously shouldn't happen.
I would have liked to add a test to cover this case, but I'm afraid I couldn't work out how to force the `org.httpkit.ws.WebSocketClient` to fragment a binary frame in the necessary way. I'd be happy to add a test if someone could point me in the right direction.
=> Correctly reset fragmentedOpCode on WS frame completion.

.travis.yml, circle.yml, project.clj, test/java/org/httpkit/ws/WebSocketClient.java, test/org/httpkit/server_test.clj
I've been testing http-kit's tests on CircleCI and they don't seem to be running into the same timeout issues that afflicted us on Travis. They're also free for open source so I just suggest we set that up as our CI server instead of Travis.
=> [circleci] Move to CircleCI

.travis.yml, circle.yml, project.clj, test/java/org/httpkit/ws/WebSocketClient.java, test/org/httpkit/server_test.clj
Reverts http-kit/http-kit#270
I like CircleCI a lot as a product - I think it's the best available - but there's no real reason for us to switch here. Reverting my prior commit.
=> Revert "[circleci] Move to CircleCI"

src/java/org/httpkit/server/AsyncChannel.java
Therefore the transfer-encoding header is only send in this version.
=> Transfer-Encoding is only supported in HTTP Version 1.1.

src/java/org/httpkit/BytesInputStream.java
At my company, we use the length of inputs to do load estimation on our backend. As of right now, there is no easy way to access the length of a BytesInputStream other than calling toString on it, and parsing out the returned length. 
This PR provides an accessor to count in BytesInputStream. Since it is already exposed in toString, I figured it would not be a problem.
I'm eager to get this in, let me know if there are any changes you'd like! Or, if you'd prefer some alternative approach, let me know and I'll do things your way.
=> Added a getCount method to BytesInputStream

src/java/org/httpkit/HttpUtils.java, test/org/httpkit/server_test.clj
Why? With libs like [jsonista](https://github.com/metosin/jsonista), the fastest way to serialize Clojure/EDN data is to write it directly into `byte[]`. Aleph and the next version Immutant support this already.
Ported the top3 Clojure Entries in [techempower web benchmarks](https://www.techempower.com/benchmarks/) to Jsonista + `byte[]`:
=> support byte[] responses

src/org/httpkit/server.clj
This is an attempt to address #318, and an alternative to #391.
In contrast to #391, this approach:
- Avoids a breaking change by keeping the old (racey) behaviour
by default.
- Offers a new API (`as-channel`) with explicit pre/post WebSocket
handshake handlers.
Another alternative would be to (re)introduce a queue as discussed at
#318 (comment), but would be a fair bit of complexity.
=> [Experimental] `as-channel` API to address [#318]

README.md
Project website was using the github.com domain instead of GitHub.io.
=> Correct project website url
